//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.14 at 10:34:59 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.quinnox.com/purchaseOrder")
package com.quinnox.binding;
